directories:
  pkl: develop/models/rand_forest.pkl
  train_data: develop/data/turnover.csv
  names: develop/data/random-names.csv
  log: develop/logs/develop.log

model:
  ntrees: 200
  seed: 45
  max_depth: 15

random: 12345

test_size: 1000